### ISSUE TITLE
Cron not reaching Docker container

### ISSUE THREAD

**Issue by ChaosExAnima** [mailpoet/mailpoet#4173]
**Describe the bug**
I'm experiencing a bug with trying to get MailPoet working on a Docker-based dev setup using PHP-FPM and nginx. Whenever I attempt to visit the MailPoet admin, I saw the following error:
```
An exception has been thrown during the rendering of a template ("Site URL is unreachable.").
```
This occurs no matter what page I attempted to access in the admin.

I checked what's going on with [Query Monitor](https://wordpress.org/plugins/query-monitor/) and discovered the culprit lay with [`CronHelper->getSiteUrl()`](https://github.com/mailpoet/mailpoet/blob/trunk/mailpoet/lib/Cron/CronHelper.php#L187).

From what I can determine, the code is attempting to access the publicly accessible URL. However, it does not account for the fact that the `site_url` is the "public" URL, which may not be accessible by PHP itself. Cases here are dev environments, but also potentially intranet sites or anything else with an atypical network layout.

As a temporary fix, I inserted `return 'http://nginx';` at the start of the method and it was happy again. I would recommend providing a way to override this method if needed with either a wp-config constant or a filter, ideally the former as it could be used as a Docker environment variable.

**To reproduce**

1. Create a local Docker setup like outlined below.
2. Attempt to set up MailPoet in the admin.

docker-compose.yml:
```yaml
version: "3.7"
services:
    wordpress:
        image: chaosexanima/transgression-wordpress
        volumes:
            - "${PWD}/wp_content:/var/www/html/wp-content"
            - wp_core:/var/www/html
            - "${PWD}/wp-config.php:/var/www/html/wp-config.php"

    nginx:
        image: nginx
        ports:
            - 8888:80
        volumes:
            - "${PWD}/wp_content:/var/www/html/wp-content"
            - "${PWD}/wp-config.php:/var/www/html/wp-config.php:ro"
            - wp_core:/var/www/html
```

Notes:
- I omitted the full Compose file for brevity, as well as the nginx config. It's pretty standard, and I can provide if needed.
- [Here is the Dockerfile](https://github.com/ChaosExAnima/docker-forks/blob/main/transgression/Dockerfile) for the above image. The only thing it really does is load in PDO_Mysql, as otherwise MailPoet gets sad. 

**Actual behavior**
Every single admin page had a fatal error when it attempted to initialize the Cron daemon.

**Expected behavior**
Things to work!

**Screenshots**
<img width="707" alt="Screen Shot 2022-06-01 at 10 17 25 PM" src="https://user-images.githubusercontent.com/1760168/171535375-1cf696c3-888e-4e53-9d6c-9a66ab3c0f9d.png">

**Versions (please complete the following information):**

- WordPress version: 6.0
- PHP version: 8.0-fpm
- MailPoet version: 3.89.3

**Additional context**
<details>
<summary>Full stack trace from Query Monitor</summary>
<pre>

fsockopen(): Unable to connect to localhost:8888 (Address not available)

wp-content/plugins/mailpoet/lib/Cron/CronHelper.php:209
fsockopen()
wp-content/plugins/mailpoet/lib/Cron/CronHelper.php:209
MailPoet\C\CronHelper->getSiteUrl()
wp-content/plugins/mailpoet/lib/Cron/CronHelper.php:186
MailPoet\C\CronHelper->getCronUrl()
wp-content/plugins/mailpoet/lib/Helpscout/Beacon.php:51
MailPoet\H\Beacon->getData()
wp-content/plugins/mailpoet/lib/Twig/Helpscout.php:24
MailPoet\T\Helpscout->getHelpscoutData()
wp-content/uploads/mailpoet/cache/d0/d0c13051e4cd39528ef30e287ea8a1e9adc506b6fd198d7c2501e79943ed44f7.php:268
__TwigTemplate_7b37297af610553caa0fa74e16d8e7862a590e79ef00b9707bb2aef12e2f1ea7->doDisplay()
wp-content/plugins/mailpoet/vendor-prefixed/twig/twig/src/Template.php:223
MailPoetVendor\T\Template->displayWithErrorHandling()
wp-content/plugins/mailpoet/vendor-prefixed/twig/twig/src/Template.php:198
MailPoetVendor\T\Template->display()
wp-content/uploads/mailpoet/cache/8f/8f34bed73ce398192db017abd561b0a23a30dc4a6a35a9125d5236b6a71465d2.php:44
__TwigTemplate_b066cb629a4cdc788ffdfe30a3bf5ead45f0d9c218b8b52b8796ac9b6a09d0c9->doDisplay()
wp-content/plugins/mailpoet/vendor-prefixed/twig/twig/src/Template.php:223
MailPoetVendor\T\Template->displayWithErrorHandling()
wp-content/plugins/mailpoet/vendor-prefixed/twig/twig/src/Template.php:198
MailPoetVendor\T\Template->display()
wp-content/plugins/mailpoet/vendor-prefixed/twig/twig/src/Template.php:211
MailPoetVendor\T\Template->render()
wp-content/plugins/mailpoet/vendor-prefixed/twig/twig/src/TemplateWrapper.php:17
MailPoetVendor\T\TemplateWrapper->render()
wp-content/plugins/mailpoet/vendor-prefixed/twig/twig/src/Environment.php:128
MailPoetVendor\T\Environment->render()
wp-content/plugins/mailpoet/lib/Config/Renderer.php:111
MailPoet\C\Renderer->render()
wp-content/plugins/mailpoet/lib/AdminPages/PageRenderer.php:89
MailPoet\A\PageRenderer->displayPage()
wp-content/plugins/mailpoet/lib/AdminPages/Pages/Newsletters.php:189
MailPoet\A\P\Newsletters->render()
wp-content/plugins/mailpoet/lib/Config/Menu.php:497
MailPoet\C\Menu->newsletters()
wp-includes/class-wp-hook.php:307
do_action('toplevel_page_mailpoet-newsletters')
wp-admin/admin.php:259
</pre>
</details>
